# config
cover: /img/bg_img.jpg
logo: /img/logo.png
top_saying:
- title: 顺其自然是竭尽所能后的不强求，而不是两手一摊的不作为。
- content: Let nature take its course is after doing everything they can to try not to demand, and get rather than his hands a pool of inaction.

bottom_saying: Thank you for viewing.
# Content
excerpt_link: Read More

rss: /

highlightjs: vs

#Works
# works:
# - works_name: javaScript
#   works_url: /
# - works_name: canvas画布
#   works_url: /categories/canvas

#duoshuo name
duoshuo:

#disqus name
disqus_shortname:

#fancybox
fancybox: false

# Miscellaneous
github: https://github.com/limenglin0717
# twitter: https://twitter.com/
# facebook: https://www.facebook.com/
# google: https://google.com/
# weibo: http://weibo.com/CSLBL?refer_flag=1001030201_

#about  timeline
timeline:
- num: 1
  word: 2014/06/12-Start
- num: 2
  word: 2014/11/29-XXX
- num: 3
  word: 2015/02/18-DDD
- num: 4
  word: More

#Links
# links:
# - name: Kieran
#   link: http://go.kieran.top/
# - name: Name
#   link: http://domain.com/
